// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Heb8EnLBZPOB4fQ2-QnUsun2KheWVeU',
    appId: '1:445983747664:web:31a91c4441a01fe953ab55',
    messagingSenderId: '445983747664',
    projectId: 'aims-2-a973c',
    authDomain: 'aims-2-a973c.firebaseapp.com',
    storageBucket: 'aims-2-a973c.firebasestorage.app',
    measurementId: 'G-KH2S2YDBMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhLLNE6L6Tc2TwrnURkoKXQu3dhX3h6L4',
    appId: '1:445983747664:android:4e0e03215d43dbdc53ab55',
    messagingSenderId: '445983747664',
    projectId: 'aims-2-a973c',
    storageBucket: 'aims-2-a973c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYBMpj68qYxBoNHg3avz-HpVMWo6hH1TA',
    appId: '1:445983747664:ios:55561d8a33dac43353ab55',
    messagingSenderId: '445983747664',
    projectId: 'aims-2-a973c',
    storageBucket: 'aims-2-a973c.firebasestorage.app',
    iosBundleId: 'com.leos.aims2.aims2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYBMpj68qYxBoNHg3avz-HpVMWo6hH1TA',
    appId: '1:445983747664:ios:55561d8a33dac43353ab55',
    messagingSenderId: '445983747664',
    projectId: 'aims-2-a973c',
    storageBucket: 'aims-2-a973c.firebasestorage.app',
    iosBundleId: 'com.leos.aims2.aims2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Heb8EnLBZPOB4fQ2-QnUsun2KheWVeU',
    appId: '1:445983747664:web:09e6f6c9d0b7986653ab55',
    messagingSenderId: '445983747664',
    projectId: 'aims-2-a973c',
    authDomain: 'aims-2-a973c.firebaseapp.com',
    storageBucket: 'aims-2-a973c.firebasestorage.app',
    measurementId: 'G-TPPM05G2SY',
  );

}