import 'dart:io';
import 'dart:typed_data';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:printing/printing.dart';

import '../providers/accounts_provider.dart';
import '../providers/items_provider.dart';
import '../models/ItemModel.dart';

class InventoryTransactionReportController {
  static const int expiryWarningDays = 30;

  static Future<void> generateInventoryReport(
      BuildContext context, {
        required DateTime start,
        required DateTime end,
      }) async {
    final inventoryProvider = context.read<InventoryProvider>();
    final items = inventoryProvider.items;

    final now = DateTime.now();
    final dateFormat = DateFormat('yyyy-MM-dd');

    // ================= FILTERS =================
    final allItems = items;

    final lowStockItems = items.where((i) => i.isLowStock).toList();

    final outOfStockItems = items.where((i) => i.isOutOfStock).toList();

    final accountProvider = context.read<AccountsProvider>();

    final generatedBy =
        accountProvider.currentUser?.fullName ?? 'Unknown User';



    final nearlyExpiryItems = items.where((item) {


      final expiry = item.nearestExpiry;
      if (expiry == null) return false;
      final daysLeft = expiry.difference(now).inDays;
      return daysLeft >= 0 && daysLeft <= expiryWarningDays;
    }).toList();

    // ================= PDF SETUP =================
    final font = await PdfGoogleFonts.robotoRegular();
    final boldFont = await PdfGoogleFonts.robotoBold();

    final pdf = pw.Document();

    pw.Widget buildTable(String title, List<ItemModel> data) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            '$title (${data.length})',
            style: pw.TextStyle(font: boldFont, fontSize: 14),
          ),
          pw.SizedBox(height: 6),
          data.isEmpty
              ? pw.Text(
            'No records',
            style: pw.TextStyle(font: font, fontSize: 10),
          )
              : pw.Table.fromTextArray(
            headerStyle:
            pw.TextStyle(font: boldFont, fontSize: 10),
            cellStyle:
            pw.TextStyle(font: font, fontSize: 9),
            headers: const [
              'Item',
              'Category',
              'Total Stock',
              'Low Stock Threshold',
              'Nearest Expiry',
            ],
            data: data.map((item) {
              return [
                item.name,
                item.category,
                item.totalStock.toString(),
                item.resolvedLowStockThreshold.toString(),
                item.nearestExpiry == null
                    ? '-'
                    : dateFormat.format(item.nearestExpiry!),
              ];
            }).toList(),
          ),
          pw.SizedBox(height: 16),
        ],
      );
    }

    // ================= PAGE =================
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (_) => [
          pw.Text(
            'Inventory Report',
            style: pw.TextStyle(font: boldFont, fontSize: 22),
          ),


          pw.SizedBox(height: 4),

          pw.Text(
            'Report Generated by: $generatedBy',
            style: pw.TextStyle(
              font: font,
              fontSize: 11,
              color: PdfColors.grey700,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            'From ${dateFormat.format(start)} to ${dateFormat.format(end)}',
            style: pw.TextStyle(font: font, fontSize: 12),
          ),
          pw.SizedBox(height: 20),

          // -------- SUMMARY --------
          pw.Text(
            'Summary',
            style: pw.TextStyle(font: boldFont, fontSize: 16),
          ),
          pw.SizedBox(height: 8),
          pw.Bullet(
            text: 'Total Items: ${allItems.length}',
            style: pw.TextStyle(font: font),
          ),
          pw.Bullet(
            text: 'Low Stock Items: ${lowStockItems.length}',
            style: pw.TextStyle(font: font),
          ),
          pw.Bullet(
            text: 'Out of Stock Items: ${outOfStockItems.length}',
            style: pw.TextStyle(font: font),
          ),
          pw.Bullet(
            text: 'Nearly Expiry Items: ${nearlyExpiryItems.length}',
            style: pw.TextStyle(font: font),
          ),

          pw.SizedBox(height: 20),

          // -------- TABLES --------
          buildTable('All Items', allItems),
          buildTable('Low Stock Items', lowStockItems),
          buildTable('Out of Stock Items', outOfStockItems),
          buildTable('Nearly Expiry Items', nearlyExpiryItems),
        ],
      ),
    );

    final pdfBytes =
    Uint8List.fromList(await pdf.save());

    _showPreviewDialog(
      context,
      pdfBytes,
      'inventory_report_${dateFormat.format(start)}_${dateFormat.format(end)}.pdf',
    );
  }

  // ================= PREVIEW =================
  static void _showPreviewDialog(
      BuildContext context,
      Uint8List pdfBytes,
      String fileName,
      ) {
    showDialog(
      context: context,
      builder: (_) => Dialog(
        insetPadding: const EdgeInsets.all(20),
        child: SizedBox(
          width: 1000,
          height: 650,
          child: Column(
            children: [
              // ================= HEADER =================
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                color: Colors.grey.shade200,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      'Inventory Report Preview',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                      ),
                    ),

          Row(
            children: [
              TextButton.icon(
                icon: const Icon(Icons.download),
                label: const Text('Save'),
                onPressed: () async {
                  try {
                    // 1️⃣ Ask WHERE to save
                    final String? folderPath =
                    await FilePicker.platform.getDirectoryPath(
                      dialogTitle: 'Choose where to save the report',
                    );

                    if (folderPath == null) return; // user cancelled

                    // 2️⃣ Create file path
                    final filePath = '$folderPath/$fileName';

                    final file = File(filePath);

                    // 3️⃣ Save file
                    await file.writeAsBytes(pdfBytes);

                    if (!context.mounted) return;
                    Navigator.pop(context);

                    // 4️⃣ Success feedback
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        content: Text('Saved to:\n$filePath'),
                        action: SnackBarAction(
                          label: 'Open',
                          onPressed: () => _openInExplorer(filePath),
                        ),
                      ),
                    );
                  } catch (e) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text('Failed to save file: $e')),
                    );
                  }
                },
              ),

              TextButton(
                child: const Text('Close'),
                onPressed: () => Navigator.pop(context),
              ),
            ],
          ),


                  ],
                ),
              ),

              // ================= PDF PREVIEW =================
              Expanded(
                child: PdfPreview(
                  build: (_) async => pdfBytes,

                  // ❌ disable built-in controls
                  allowPrinting: false,
                  allowSharing: false,
                  canChangeOrientation: false,
                  canChangePageFormat: false,
                  canDebug: false,

                  // ❌ hide toolbar completely
                  actions: const [],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

}

void _openInExplorer(String path) async {
  final file = File(path);
  if (!file.existsSync()) return;

  if (Platform.isWindows) {
    await Process.run(
      'explorer',
      ['/select,', file.path],
      runInShell: true,
    );
  } else if (Platform.isMacOS) {
    await Process.run(
      'open',
      ['-R', file.path],
    );
  } else if (Platform.isLinux) {
    await Process.run(
      'xdg-open',
      [file.parent.path],
    );
  }
}

Future<void> openInFileExplorer(String filePath) async {
  final file = File(filePath);

  if (!await file.exists()) return;

  if (Platform.isWindows) {
    // Opens Explorer and selects the file
    await Process.run(
      'explorer',
      ['/select,', file.path],
      runInShell: true,
    );
  } else if (Platform.isMacOS) {
    // Opens Finder and selects the file
    await Process.run(
      'open',
      ['-R', file.path],
    );
  } else if (Platform.isLinux) {
    // Opens containing folder
    await Process.run(
      'xdg-open',
      [file.parent.path],
    );
  }
}

